-- FAQ Export - Generated 2025-12-25T01:04:23.726643Z
-- Total FAQs: 44
--
-- This file was auto-generated by `mix faq.export_sql`
--
-- Usage: psql $DATABASE_URL < this_file.sql

BEGIN;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'admin-dashboard-access',
  'admin',
  'How do I access the admin dashboard?',
  'Miten pääsen ylläpidon kojelaudalle?',
  '<p>The admin dashboard is accessible only to users with admin privileges:</p>
<ol>
  <li>Log in with an admin account</li>
  <li>Click "Admin" in the navigation menu</li>
  <li>You''ll see the admin dashboard with management options</li>
</ol>
<p><strong>Admin dashboard features:</strong></p>
<ul>
  <li>User management and overview</li>
  <li>Invitation code management</li>
  <li>FAQ management</li>
  <li>Feedback review</li>
  <li>System analytics</li>
</ul>
<p><strong>Note:</strong> The "Admin" link only appears for users with admin role.</p>
',
  '<p>Ylläpidon kojelauta on saatavilla vain ylläpitäjän oikeuksilla:</p>
<ol>
  <li>Kirjaudu ylläpitäjätilillä</li>
  <li>Klikkaa "Ylläpito" navigaatiovalikossa</li>
  <li>Näet ylläpidon kojelaudan hallintatoiminnoilla</li>
</ol>
<p><strong>Ylläpidon kojelaudan ominaisuudet:</strong></p>
<ul>
  <li>Käyttäjien hallinta ja yleiskatsaus</li>
  <li>Kutsukoodien hallinta</li>
  <li>UKK:n hallinta</li>
  <li>Palautteen tarkastelu</li>
  <li>Järjestelmäanalytiikka</li>
</ul>
<p><strong>Huomaa:</strong> "Ylläpito"-linkki näkyy vain ylläpitäjän roolilla oleville käyttäjille.</p>
',
  1000,
  true,
  '2025-12-08T12:14:39Z',
  '2025-12-08T12:14:39Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'manage-invitation-codes',
  'admin',
  'How do I create and manage invitation codes?',
  'Miten luon ja hallinnoin kutsukoodeja?',
  '<p>Invitation codes control user registration. To manage them:</p>
<h4>Creating a new code:</h4>
<ol>
  <li>Go to Admin → Invitations</li>
  <li>Click "New Invitation"</li>
  <li>Configure options:
    <ul>
      <li><strong>Code:</strong> Auto-generated or custom (XXXX-XXXX-XXXX format)</li>
      <li><strong>Max uses:</strong> Limit how many times the code can be used</li>
      <li><strong>Expiration:</strong> Set an expiry date (optional)</li>
      <li><strong>Default role:</strong> User or admin</li>
    </ul>
  </li>
  <li>Click "Create"</li>
</ol>
<h4>Managing existing codes:</h4>
<ul>
  <li>View usage statistics for each code</li>
  <li>Deactivate codes that shouldn''t be used anymore</li>
  <li>Track who used each code</li>
</ul>
',
  '<p>Kutsukoodit hallitsevat käyttäjien rekisteröitymistä. Hallinnoidaksesi niitä:</p>
<h4>Uuden koodin luominen:</h4>
<ol>
  <li>Mene Ylläpito → Kutsut</li>
  <li>Klikkaa "Uusi kutsu"</li>
  <li>Määritä asetukset:
    <ul>
      <li><strong>Koodi:</strong> Automaattisesti luotu tai mukautettu (XXXX-XXXX-XXXX-muoto)</li>
      <li><strong>Käyttökerrat:</strong> Rajoita kuinka monta kertaa koodia voi käyttää</li>
      <li><strong>Vanheneminen:</strong> Aseta vanhenemispäivä (valinnainen)</li>
      <li><strong>Oletusrooli:</strong> Käyttäjä tai ylläpitäjä</li>
    </ul>
  </li>
  <li>Klikkaa "Luo"</li>
</ol>
<h4>Olemassa olevien koodien hallinta:</h4>
<ul>
  <li>Katso käyttötilastoja kullekin koodille</li>
  <li>Poista käytöstä koodit, joita ei pitäisi enää käyttää</li>
  <li>Seuraa kuka käytti mitäkin koodia</li>
</ul>
',
  1010,
  true,
  '2025-12-08T12:14:39Z',
  '2025-12-08T12:14:39Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'manage-users',
  'admin',
  'How do I manage users?',
  'Miten hallinnoin käyttäjiä?',
  '<p>User management is available in the admin dashboard:</p>
<h4>Viewing users:</h4>
<ol>
  <li>Go to Admin → Users</li>
  <li>Browse the user list with sorting and filtering</li>
  <li>Click a user to see their details</li>
</ol>
<h4>User information shown:</h4>
<ul>
  <li>Email and username</li>
  <li>Registration date</li>
  <li>Role (user/admin)</li>
  <li>Confirmation status</li>
  <li>Post count and activity</li>
  <li>Invitation code used</li>
</ul>
<h4>Admin actions:</h4>
<ul>
  <li>View user''s posts and content</li>
  <li>Check user activity log</li>
  <li>Manage user role if needed</li>
</ul>
',
  '<p>Käyttäjien hallinta on saatavilla ylläpidon kojelaudalla:</p>
<h4>Käyttäjien katselu:</h4>
<ol>
  <li>Mene Ylläpito → Käyttäjät</li>
  <li>Selaa käyttäjälistaa lajittelun ja suodatuksen avulla</li>
  <li>Klikkaa käyttäjää nähdäksesi heidän tietonsa</li>
</ol>
<h4>Näytettävät käyttäjätiedot:</h4>
<ul>
  <li>Sähköposti ja käyttäjätunnus</li>
  <li>Rekisteröitymispäivä</li>
  <li>Rooli (käyttäjä/ylläpitäjä)</li>
  <li>Vahvistustila</li>
  <li>Julkaisumäärä ja aktiivisuus</li>
  <li>Käytetty kutsukoodi</li>
</ul>
<h4>Ylläpitotoiminnot:</h4>
<ul>
  <li>Katso käyttäjän julkaisuja ja sisältöä</li>
  <li>Tarkista käyttäjän toimintaloki</li>
  <li>Hallitse käyttäjän roolia tarvittaessa</li>
</ul>
',
  1020,
  true,
  '2025-12-08T12:14:39Z',
  '2025-12-08T12:14:39Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'manage-faqs',
  'admin',
  'How do I create and manage FAQs?',
  'Miten luon ja hallinnoin UKK:ta?',
  '<p>FAQs help users find answers quickly. Here''s how to manage them:</p>
<h4>Creating a FAQ:</h4>
<ol>
  <li>Go to FAQs page as an admin</li>
  <li>Click "New FAQ"</li>
  <li>Fill in both English and Finnish versions:
    <ul>
      <li>Question (EN and FI)</li>
      <li>Answer (EN and FI) - supports HTML formatting</li>
    </ul>
  </li>
  <li>Choose category: "user" (public) or "admin" (admin-only)</li>
  <li>Set display order (lower numbers appear first)</li>
  <li>Click "Save"</li>
</ol>
<h4>FAQ categories:</h4>
<ul>
  <li><strong>User FAQs:</strong> Visible to everyone on /faqs</li>
  <li><strong>Admin FAQs:</strong> Only visible to admin users</li>
</ul>
<h4>Tips:</h4>
<ul>
  <li>Use HTML for formatting (lists, bold, links)</li>
  <li>Keep answers concise but complete</li>
  <li>Update FAQs when features change</li>
</ul>
',
  '<p>UKK:t auttavat käyttäjiä löytämään vastauksia nopeasti. Näin hallinnoit niitä:</p>
<h4>UKK:n luominen:</h4>
<ol>
  <li>Mene UKK-sivulle ylläpitäjänä</li>
  <li>Klikkaa "Uusi UKK"</li>
  <li>Täytä sekä englannin- että suomenkieliset versiot:
    <ul>
      <li>Kysymys (EN ja FI)</li>
      <li>Vastaus (EN ja FI) - tukee HTML-muotoilua</li>
    </ul>
  </li>
  <li>Valitse kategoria: "user" (julkinen) tai "admin" (vain ylläpitäjät)</li>
  <li>Aseta näyttöjärjestys (pienemmät numerot näkyvät ensin)</li>
  <li>Klikkaa "Tallenna"</li>
</ol>
<h4>UKK-kategoriat:</h4>
<ul>
  <li><strong>Käyttäjä-UKK:t:</strong> Näkyvät kaikille osoitteessa /faqs</li>
  <li><strong>Ylläpitäjä-UKK:t:</strong> Näkyvät vain ylläpitäjille</li>
</ul>
<h4>Vinkkejä:</h4>
<ul>
  <li>Käytä HTML:ää muotoiluun (listat, lihavointi, linkit)</li>
  <li>Pidä vastaukset ytimekkäinä mutta kattavina</li>
  <li>Päivitä UKK:t kun ominaisuudet muuttuvat</li>
</ul>
',
  1030,
  true,
  '2025-12-08T12:14:39Z',
  '2025-12-08T12:14:39Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'review-feedback',
  'admin',
  'How do I review user feedback?',
  'Miten tarkastelen käyttäjäpalautetta?',
  '<p>User feedback helps improve the platform. To review it:</p>
<ol>
  <li>Go to Admin → Feedback</li>
  <li>Browse submitted feedback entries</li>
  <li>Filter by date, rating, or testimonial status</li>
</ol>
<h4>Feedback information includes:</h4>
<ul>
  <li>User''s happiness rating (1-5 scale)</li>
  <li>Written feedback and suggestions</li>
  <li>Whether it''s approved as a testimonial</li>
  <li>Submission date and user info</li>
</ul>
<h4>Managing testimonials:</h4>
<ul>
  <li>Approve high-quality feedback as testimonials</li>
  <li>Approved testimonials may appear on the site</li>
  <li>Users must opt-in for testimonial use</li>
</ul>
',
  '<p>Käyttäjäpalaute auttaa parantamaan alustaa. Tarkastellaksesi sitä:</p>
<ol>
  <li>Mene Ylläpito → Palaute</li>
  <li>Selaa lähetettyjä palautteita</li>
  <li>Suodata päivämäärän, arvosanan tai suositustilan mukaan</li>
</ol>
<h4>Palautetiedot sisältävät:</h4>
<ul>
  <li>Käyttäjän tyytyväisyysarvosana (1-5 asteikko)</li>
  <li>Kirjallinen palaute ja ehdotukset</li>
  <li>Onko hyväksytty suositukseksi</li>
  <li>Lähetyspäivä ja käyttäjätiedot</li>
</ul>
<h4>Suositusten hallinta:</h4>
<ul>
  <li>Hyväksy laadukas palaute suositukseksi</li>
  <li>Hyväksytyt suositukset voivat näkyä sivustolla</li>
  <li>Käyttäjien on annettava suostumus suosituskäyttöön</li>
</ul>
',
  1040,
  true,
  '2025-12-08T12:14:39Z',
  '2025-12-08T12:14:39Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'view-analytics',
  'admin',
  'How do I view system analytics?',
  'Miten katson järjestelmäanalytiikkaa?',
  '<p>System analytics provide insights into platform usage:</p>
<h4>Available metrics:</h4>
<ul>
  <li><strong>User statistics:</strong> Total users, new registrations, active users</li>
  <li><strong>Content metrics:</strong> Total posts, posts per user, popular tags</li>
  <li><strong>Activity logs:</strong> Recent actions, login history</li>
  <li><strong>Feed statistics:</strong> Active feeds, refresh rates, error rates</li>
  <li><strong>Search analytics:</strong> Popular search terms, search volume</li>
</ul>
<h4>Accessing analytics:</h4>
<ol>
  <li>Go to Admin → Dashboard</li>
  <li>View overview statistics on the main panel</li>
  <li>Click into specific sections for detailed reports</li>
</ol>
<p>Analytics help identify popular content, user engagement patterns, and potential issues.</p>
',
  '<p>Järjestelmäanalytiikka tarjoaa näkemyksiä alustan käytöstä:</p>
<h4>Saatavilla olevat mittarit:</h4>
<ul>
  <li><strong>Käyttäjätilastot:</strong> Käyttäjämäärä, uudet rekisteröitymiset, aktiiviset käyttäjät</li>
  <li><strong>Sisältömittarit:</strong> Julkaisumäärä, julkaisut per käyttäjä, suositut tagit</li>
  <li><strong>Toimintalokit:</strong> Viimeaikaiset toiminnot, kirjautumishistoria</li>
  <li><strong>Syötetilastot:</strong> Aktiiviset syötteet, päivitystiheydet, virheprosentit</li>
  <li><strong>Hakuanalytiikka:</strong> Suositut hakutermit, hakumäärät</li>
</ul>
<h4>Analytiikan käyttö:</h4>
<ol>
  <li>Mene Ylläpito → Kojelauta</li>
  <li>Katso yleiskatsaustilastot pääpaneelista</li>
  <li>Klikkaa tiettyihin osioihin yksityiskohtaisiin raportteihin</li>
</ol>
<p>Analytiikka auttaa tunnistamaan suosittua sisältöä, käyttäjien sitoutumismalleja ja mahdollisia ongelmia.</p>
',
  1050,
  true,
  '2025-12-08T12:14:39Z',
  '2025-12-08T12:14:39Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'how-to-create-first-post',
  'user',
  'How do I create my first blog post?',
  'Miten luon ensimmäisen blogikirjoitukseni?',
  '<p>To create your first blog post on Portal of JH:</p>
<ol>
  <li>Log in to your account</li>
  <li>Click "Posts" in the navigation menu</li>
  <li>Click the "New Post" button</li>
  <li>Enter a title and write your content using Markdown</li>
  <li>Add tags to categorize your post (optional)</li>
  <li>Click "Save Post" to publish</li>
</ol>
<p>Your post will be visible on the homepage once published!</p>',
  '<p>Luodaksesi ensimmäisen blogikirjoituksesi Portal of JH:ssa:</p>
<ol>
  <li>Kirjaudu sisään tilillesi</li>
  <li>Klikkaa "Julkaisut" navigointivalikossa</li>
  <li>Klikkaa "Uusi julkaisu" -painiketta</li>
  <li>Kirjoita otsikko ja sisältö Markdown-muodossa</li>
  <li>Lisää tageja kategorisoidaksesi kirjoituksesi (valinnainen)</li>
  <li>Klikkaa "Tallenna julkaisu" julkaistaksesi</li>
</ol>
<p>Julkaisusi näkyy etusivulla kun se on julkaistu!</p>',
  1,
  true,
  '2025-11-28T14:53:38Z',
  '2025-11-28T16:18:36Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'formatting-options',
  'user',
  'What formatting options are available for my posts?',
  'Mitä muotoiluvaihtoehtoja kirjoituksilleni on saatavilla?',
  '<p>Portal of JH uses Markdown for post formatting. Here are the most common examples you can copy and use:</p>

<h3>Text Formatting</h3>
<pre><code>**Bold text**
*Italic text*
***Bold and italic***
~~Strikethrough~~</code></pre>

<h3>Headers</h3>
<pre><code># Heading 1
## Heading 2
### Heading 3</code></pre>

<h3>Links and Images</h3>
<pre><code>[Link text](https://example.com)
![Image alt text](https://example.com/image.jpg)</code></pre>

<h3>Lists</h3>
<pre><code>- Unordered item 1
- Unordered item 2
  - Nested item

1. Ordered item 1
2. Ordered item 2</code></pre>

<h3>Code</h3>
<pre><code>Inline `code` with backticks

```elixir
# Code block with syntax highlighting
def hello(name) do
  IO.puts("Hello, #{name}!")
end
```</code></pre>

<h3>Blockquotes</h3>
<pre><code>&gt; This is a quote
&gt; It can span multiple lines</code></pre>

<p>Just copy these examples and modify them for your content!</p>',
  '<p>Portal of JH käyttää Markdown-muotoilua julkaisuissa. Tässä yleisimmät esimerkit joita voit kopioida ja käyttää:</p>

<h3>Tekstin muotoilu</h3>
<pre><code>**Lihavoitu teksti**
*Kursivoitu teksti*
***Lihavoitu ja kursivoitu***
~~Yliviivattu~~</code></pre>

<h3>Otsikot</h3>
<pre><code># Otsikko 1
## Otsikko 2
### Otsikko 3</code></pre>

<h3>Linkit ja kuvat</h3>
<pre><code>[Linkin teksti](https://esimerkki.fi)
![Kuvan alt-teksti](https://esimerkki.fi/kuva.jpg)</code></pre>

<h3>Listat</h3>
<pre><code>- Järjestämätön kohta 1
- Järjestämätön kohta 2
  - Sisäkkäinen kohta

1. Järjestetty kohta 1
2. Järjestetty kohta 2</code></pre>

<h3>Koodi</h3>
<pre><code>Rivinsisäinen `koodi` backtick-merkeillä

```elixir
# Koodilohko syntaksikorostuksella
def tervehdys(nimi) do
  IO.puts("Hei, #{nimi}!")
end
```</code></pre>

<h3>Lainaukset</h3>
<pre><code>&gt; Tämä on lainaus
&gt; Se voi olla useammalla rivillä</code></pre>

<p>Kopioi nämä esimerkit ja muokkaa niitä sisällöllesi!</p>',
  2,
  true,
  '2025-11-28T14:53:38Z',
  '2025-11-28T14:53:38Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'how-tags-work',
  'user',
  'How do tags work?',
  'Miten tagit toimivat?',
  '<p>Tags help organize and categorize your posts. You can:</p>
<ul>
  <li>Create tags from the Tags page</li>
  <li>Assign multiple tags to each post</li>
  <li>Use tags to filter and find related posts</li>
  <li>Each tag can have a custom color and description</li>
</ul>
<p>Readers can click on tags to see all posts with that tag.</p>
',
  '<p>Tagit auttavat organisoimaan ja luokittelemaan kirjoituksiasi. Voit:</p>
<ul>
  <li>Luoda tageja Tagit-sivulta</li>
  <li>Liittää useita tageja jokaiseen kirjoitukseen</li>
  <li>Käyttää tageja suodattamaan ja löytämään liittyviä kirjoituksia</li>
  <li>Jokaisella tagilla voi olla oma väri ja kuvaus</li>
</ul>
<p>Lukijat voivat klikata tageja nähdäkseen kaikki kyseisellä tagilla merkityt kirjoitukset.</p>
',
  3,
  true,
  '2025-11-28T14:53:38Z',
  '2025-11-28T14:53:38Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'post-privacy',
  'user',
  'Who can see my posts?',
  'Kuka voi nähdä kirjoitukseni?',
  '<p>Published posts are publicly visible to anyone visiting the site. Draft posts are only visible to you.</p>
<p>You have full control over:</p>
<ul>
  <li>When to publish (publish immediately or schedule)</li>
  <li>Keeping posts as drafts</li>
  <li>Editing or deleting published posts</li>
</ul>
<p>Your profile information (display name, bio, avatar) is also publicly visible.</p>
',
  '<p>Julkaistut kirjoitukset ovat julkisesti näkyvissä kaikille sivustolla vierailijoille. Luonnokset ovat vain sinun nähtävillä.</p>
<p>Sinulla on täysi kontrolli:</p>
<ul>
  <li>Julkaisuajankohta (julkaise heti tai aikatauluta)</li>
  <li>Kirjoitusten pitäminen luonnoksina</li>
  <li>Julkaistujen kirjoitusten muokkaus tai poisto</li>
</ul>
<p>Profiilitietosi (näyttönimi, kuvaus, avatar) ovat myös julkisesti näkyvissä.</p>
',
  4,
  true,
  '2025-11-28T14:53:38Z',
  '2025-11-28T14:53:38Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'rss-subscription',
  'user',
  'Can readers subscribe to my blog?',
  'Voivatko lukijat tilata blogini?',
  '<p>Yes! Portal of JH provides multiple subscription options:</p>
<ul>
  <li><strong>RSS Feed:</strong> Subscribe to receive updates in your RSS reader</li>
  <li><strong>Atom Feed:</strong> Alternative XML feed format</li>
  <li><strong>JSON Feed:</strong> Modern JSON-based feed format</li>
</ul>
<p>Feed links are available in the footer of every page. Each post includes reading time estimates to help you plan your reading!</p>',
  '<p>Kyllä! Portal of JH tarjoaa useita tilausvaihtoehtoja:</p>
<ul>
  <li><strong>RSS-syöte:</strong> Tilaa päivitykset RSS-lukijallesi</li>
  <li><strong>Atom-syöte:</strong> Vaihtoehtoinen XML-syöteformaatti</li>
  <li><strong>JSON-syöte:</strong> Moderni JSON-pohjainen syöte</li>
</ul>
<p>Syötelinkit löytyvät jokaisen sivun alatunnisteesta. Jokainen julkaisu sisältää lukuajan arvion lukemisen suunnitteluun!</p>',
  5,
  true,
  '2025-11-28T14:53:38Z',
  '2025-11-28T14:53:38Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'customize-profile',
  'user',
  'How do I customize my profile?',
  'Miten mukautan profiiliani?',
  '<p>Go to Settings to customize your profile:</p>
<ul>
  <li><strong>Display Name</strong> - How you appear to readers</li>
  <li><strong>Avatar</strong> - Profile picture (upload an image)</li>
  <li><strong>Bio</strong> - Short description about yourself</li>
  <li><strong>Social Links</strong> - Bluesky and Mastodon handles</li>
  <li><strong>Website URL</strong> - Link to your personal site</li>
</ul>
<p>Remember to click "Update Profile" to save your changes!</p>
',
  '<p>Mene Asetuksiin mukauttaaksesi profiiliasi:</p>
<ul>
  <li><strong>Näyttönimi</strong> - Miten näyt lukijoille</li>
  <li><strong>Avatar</strong> - Profiilikuva (lataa kuva)</li>
  <li><strong>Kuvaus</strong> - Lyhyt kuvaus itsestäsi</li>
  <li><strong>Some-linkit</strong> - Bluesky- ja Mastodon-käyttäjätunnukset</li>
  <li><strong>Verkkosivun URL</strong> - Linkki henkilökohtaiselle sivustollesi</li>
</ul>
<p>Muista klikata "Päivitä profiili" tallentaaksesi muutokset!</p>
',
  6,
  true,
  '2025-11-28T14:53:38Z',
  '2025-11-28T14:53:38Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'external-feeds',
  'user',
  'What are External Feeds?',
  'Mitä ovat Ulkoiset Syötteet?',
  '<p>External Feeds let you aggregate content from other sources into your dashboard:</p>
<ul>
  <li><strong>RSS/Atom Feeds</strong> - Subscribe to any blog or news site</li>
  <li><strong>JSON Feeds</strong> - Modern feed format support</li>
  <li><strong>Bluesky</strong> - Coming soon</li>
  <li><strong>Mastodon</strong> - Coming soon</li>
</ul>
<p>View all your feeds in one place and stay updated with content you care about.</p>
',
  '<p>Ulkoiset Syötteet mahdollistavat sisällön kokoamisen muista lähteistä kojelaudallesi:</p>
<ul>
  <li><strong>RSS/Atom-syötteet</strong> - Tilaa mikä tahansa blogi tai uutissivusto</li>
  <li><strong>JSON-syötteet</strong> - Modernin syöteformaatin tuki</li>
  <li><strong>Bluesky</strong> - Tulossa pian</li>
  <li><strong>Mastodon</strong> - Tulossa pian</li>
</ul>
<p>Katso kaikki syötteesi yhdestä paikasta ja pysy ajan tasalla sinua kiinnostavasta sisällöstä.</p>
',
  7,
  true,
  '2025-11-28T14:53:38Z',
  '2025-11-28T14:53:38Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'supported-social-media-platforms',
  'user',
  'What social media platforms are supported by the feed adapters?',
  'Mitä sosiaalisen median alustoja syötteenadapterit tukevat?',
  'The system supports 6 platforms: RSS/Atom/JSON feeds (for blogs and websites),
Mastodon (Fediverse network), Bluesky (AT Protocol), YouTube (channel feeds),
Twitter/X (via RSS bridges), and Instagram (via RSS bridges). Each platform has
different configuration requirements - RSS needs a feed URL, while Mastodon and
Bluesky need usernames.
',
  'Järjestelmä tukee 6 alustaa: RSS/Atom/JSON-syötteet (blogit ja verkkosivustot),
Mastodon (Fediverse-verkko), Bluesky (AT-protokolla), YouTube (kanava-syötteet),
Twitter/X (RSS-siltojen kautta) ja Instagram (RSS-siltojen kautta). Jokaisella
alustalla on erilaiset konfiguraatiovaatimukset - RSS tarvitsee syötteen URL:n,
kun taas Mastodon ja Bluesky tarvitsevat käyttäjätunnuksen.
',
  10,
  true,
  '2025-12-01T13:10:41Z',
  '2025-12-01T13:10:41Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'how-to-create-portfolio-project',
  'user',
  'How do I create a portfolio project?',
  'Miten luon portfolioprojektin?',
  'To create a portfolio project:

1. Go to **Projects** in the navigation menu
2. Click **New Project**
3. Follow the 5-step wizard:
   - **Basics**: Name, description, and project type
   - **Metadata**: Category, date, and tags
   - **Team & Links**: Add collaborators and related links
   - **Settings**: Set visibility (public/private, portfolio)
   - **Content**: Add cover image and gallery photos

Enable "Portfolio" in Settings to include the project in your public portfolio gallery.',
  'Portfolioprojektin luominen:

1. Siirry **Projektit**-sivulle navigaatiovalikosta
2. Klikkaa **Uusi projekti**
3. Seuraa 5-vaiheista ohjattua toimintoa:
   - **Perustiedot**: Nimi, kuvaus ja projektityyppi
   - **Metatiedot**: Kategoria, päivämäärä ja tagit
   - **Tiimi & linkit**: Lisää yhteistyökumppanit ja linkit
   - **Asetukset**: Aseta näkyvyys (julkinen/yksityinen, portfolio)
   - **Sisältö**: Lisää kansikuva ja galleriakuvat

Ota "Portfolio" käyttöön asetuksissa sisällyttääksesi projektin julkiseen portfoliogalleriaan.',
  20,
  true,
  '2025-12-17T17:25:22Z',
  '2025-12-17T17:25:22Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'add-rss-feed',
  'user',
  'How do I add an RSS feed to my feed list?',
  'Miten lisään RSS-syötteen syöteluettelooni?',
  'Navigate to /feeds, click "New Feed Source", select "RSS" as the feed type,
enter the feed URL (e.g., https://example.com/feed.xml), give it a name, and
configure the refresh interval (default 30 minutes). Click "Save" to activate
the feed. The system will automatically fetch content based on your refresh interval.
',
  'Siirry osoitteeseen /feeds, klikkaa "New Feed Source", valitse "RSS" syötetyypiksi,
syötä syötteen URL (esim. https://example.com/feed.xml), anna sille nimi ja
määritä päivitysväli (oletus 30 minuuttia). Klikkaa "Save" aktivoidaksesi
syötteen. Järjestelmä hakee sisältöä automaattisesti määrittämäsi päivitysvälin mukaan.
',
  20,
  true,
  '2025-12-01T13:10:41Z',
  '2025-12-01T13:10:41Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'how-to-manage-project-photos',
  'user',
  'How do I add, reorder, or remove photos in a project?',
  'Miten lisään, järjestän tai poistan kuvia projektista?',
  '**Adding photos:**
1. Edit your project and go to Step 5 (Content), or click "Skip to Content"
2. Use the media picker to select images from your library

**Reordering photos:**
1. Go to your project view page (/projects/:id)
2. Hover over any image to reveal control buttons
3. Click **↑** to move up or **↓** to move down

**Removing photos:**
1. Hover over the image
2. Click the **X** button
3. Confirm the removal

Note: Removing only removes the association - the image stays in your media library.',
  '**Kuvien lisääminen:**
1. Muokkaa projektia ja siirry vaiheeseen 5 (Sisältö) tai klikkaa "Siirry sisältöön"
2. Valitse kuvat mediakirjastostasi

**Kuvien järjestäminen:**
1. Siirry projektin näkymään (/projects/:id)
2. Vie hiiri kuvan päälle nähdäksesi painikkeet
3. Klikkaa **↑** siirtääksesi ylös tai **↓** siirtääksesi alas

**Kuvien poistaminen:**
1. Vie hiiri kuvan päälle
2. Klikkaa **X**-painiketta
3. Vahvista poisto

Huom: Poistaminen poistaa vain yhteyden - kuva säilyy mediakirjastossasi.',
  21,
  true,
  '2025-12-17T17:25:22Z',
  '2025-12-17T17:25:22Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'what-is-portfolio-vs-project',
  'user',
  'What is the difference between a project and a portfolio item?',
  'Mikä ero on projektilla ja portfoliokohteella?',
  'All portfolio items are projects, but not all projects are in your portfolio.

- **Project**: A private workspace for organizing your work with media, collaborators, and metadata
- **Portfolio item**: A project marked as "Portfolio" that appears in your public portfolio gallery

To add a project to your portfolio:
1. Edit the project
2. Go to Settings (Step 4)
3. Enable both "Public" and "Portfolio"

This way you can have work-in-progress projects that aren''t yet visible to the public.',
  'Kaikki portfoliokohteet ovat projekteja, mutta kaikki projektit eivät ole portfoliossa.

- **Projekti**: Yksityinen työtila töidesi järjestämiseen medialla, yhteistyökumppaneilla ja metatiedoilla
- **Portfoliokohde**: Projekti, joka on merkitty "Portfolio"-tilaan ja näkyy julkisessa portfoliogalleriassasi

Projektin lisääminen portfolioon:
1. Muokkaa projektia
2. Siirry asetuksiin (vaihe 4)
3. Ota käyttöön sekä "Julkinen" että "Portfolio"

Näin voit pitää keskeneräisiä projekteja, jotka eivät vielä näy julkisesti.',
  22,
  true,
  '2025-12-17T17:25:22Z',
  '2025-12-17T17:25:22Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'project-tags-shared-with-posts',
  'user',
  'Are project tags the same as blog post tags?',
  'Ovatko projektien tagit samat kuin blogikirjoitusten tagit?',
  'Yes! Projects and blog posts share the same tag system.

- Tags you create for blog posts can be used in projects
- Tags you create for projects can be used in blog posts
- This helps organize all your content consistently

When adding tags to a project, you can:
- Search existing tags
- Create new tags inline
- Use public or private tags',
  'Kyllä! Projektit ja blogikirjoitukset käyttävät samaa tagijärjestelmää.

- Blogikirjoituksille luomasi tagit toimivat projekteissa
- Projekteille luomasi tagit toimivat blogikirjoituksissa
- Tämä auttaa järjestämään kaiken sisältösi johdonmukaisesti

Tageja lisätessäsi projektiin voit:
- Etsiä olemassa olevia tageja
- Luoda uusia tageja suoraan lomakkeella
- Käyttää julkisia tai yksityisiä tageja',
  23,
  true,
  '2025-12-17T17:25:22Z',
  '2025-12-17T17:25:22Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'feed-error-troubleshooting',
  'user',
  'What should I do if a feed shows an error status?',
  'Mitä teen, jos syöte näyttää virhetilaa?',
  'If a feed shows a red error badge, first check the error message by hovering
over or clicking the status. Common issues include: invalid URL (verify the
feed URL works in a browser), rate limiting (reduce refresh interval), user
not found for social platforms (check username format and account visibility),
or temporary server downtime. You can manually retry with the "Refresh Now"
button. For persistent errors, verify the source is still active and accessible.
',
  'Jos syöte näyttää punaisen virheilmoituksen, tarkista ensin virheviesti viemällä
hiiri tilan päälle tai klikkaamalla sitä. Yleisiä ongelmia ovat: virheellinen URL
(varmista, että syötte-URL toimii selaimessa), nopeudenrajoitus (pienennä
päivitysväliä), käyttäjää ei löydy sosiaalisen median alustoilla (tarkista
käyttäjätunnuksen muoto ja tilin näkyvyys) tai väliaikainen palvelinkatkos.
Voit yrittää manuaalisesti uudelleen "Refresh Now" -painikkeella. Jatkuvien
virheiden kohdalla varmista, että lähde on edelleen aktiivinen ja saatavilla.
',
  30,
  true,
  '2025-12-01T13:10:41Z',
  '2025-12-01T13:10:41Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'recommended-refresh-intervals',
  'user',
  'What is the recommended refresh interval for different feed types?',
  'Mikä on suositeltu päivitysväli eri syötetyypeille?',
  'Recommended refresh intervals: Personal blogs (60-120 minutes) - they update
infrequently, News feeds (15-30 minutes) - for timely updates, Social media
platforms like Mastodon/Bluesky (30-60 minutes) - balances freshness with API
politeness. Avoid setting intervals below 15 minutes to respect platform rate
limits and reduce unnecessary load. You can always use "Refresh Now" for
immediate updates when needed.
',
  'Suositellut päivitysvälit: Henkilökohtaiset blogit (60-120 minuuttia) - ne
päivittyvät harvoin, Uutissyötteet (15-30 minuuttia) - ajantasaisiin päivityksiin,
Sosiaalisen median alustat kuten Mastodon/Bluesky (30-60 minuuttia) - tasapainottaa
tuoreuden ja API:n kohteliaisuuden. Vältä alle 15 minuutin välejä kunnioittaaksesi
alustojen nopeudenrajoituksia ja vähentääksesi turhaa kuormaa. Voit aina käyttää
"Refresh Now" -toimintoa välittömiin päivityksiin tarvittaessa.
',
  40,
  true,
  '2025-12-01T13:10:41Z',
  '2025-12-01T13:10:41Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'add-mastodon-bluesky-feed',
  'user',
  'How do I add a Mastodon or Bluesky feed?',
  'Miten lisään Mastodon- tai Bluesky-syötteen?',
  'For Mastodon: Select "mastodon" as feed type and enter the full username with
@ prefix and instance (e.g., @elixirlang@fosstodon.org). For Bluesky: Select
"bluesky" and enter just the handle (e.g., user.bsky.social). Both use public
APIs requiring no authentication, but the account must be public (not private/protected).
The system will fetch the latest posts based on your configured refresh interval.
',
  'Mastodonille: Valitse "mastodon" syötetyypiksi ja syötä täydellinen käyttäjätunnus
@-etuliitteellä ja instanssilla (esim. @elixirlang@fosstodon.org). Blueskyllä:
Valitse "bluesky" ja syötä vain käyttäjätunnus (esim. user.bsky.social). Molemmat
käyttävät julkisia API:ita, jotka eivät vaadi todennusta, mutta tilin on oltava
julkinen (ei yksityinen/suojattu). Järjestelmä hakee uusimmat julkaisut määrittämäsi
päivitysvälin mukaan.
',
  50,
  true,
  '2025-12-01T13:10:41Z',
  '2025-12-01T13:10:41Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'setup-custom-username',
  'user',
  'How do I set up a custom username for my profile URL?',
  'Miten määritän mukautetun käyttäjätunnuksen profiili-URL:lleni?',
  'Go to /users/settings, find the "Username" field in the profile form, and
enter your desired username (3-30 characters, must start with a lowercase letter,
only lowercase letters, numbers, and underscores allowed). Click "Save Changes"
to activate. Your profile will then be accessible at /users/@yourusername in
addition to the numeric ID URL (/users/123). The username must be unique and
cannot be a reserved system word.
',
  'Siirry osoitteeseen /users/settings, etsi "Username" -kenttä profiililomakkeesta
ja syötä haluamasi käyttäjätunnus (3-30 merkkiä, aloitettava pienellä kirjaimella,
vain pienet kirjaimet, numerot ja alaviivat sallittu). Klikkaa "Save Changes"
aktivoidaksesi. Profiilisi on sitten saatavilla osoitteessa /users/@käyttäjätunnuksesi
numeerisen ID-URL:n lisäksi (/users/123). Käyttäjätunnuksen on oltava ainutlaatuinen
eikä se voi olla varattu järjestelmäsana.
',
  60,
  true,
  '2025-12-01T13:10:41Z',
  '2025-12-01T13:10:41Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'username-format-requirements',
  'user',
  'What are the username format requirements?',
  'Mitkä ovat käyttäjätunnuksen muotovaatimukset?',
  'Username must be 3-30 characters long, start with a lowercase letter (a-z),
and contain only lowercase letters, numbers, and underscores. No uppercase
letters, hyphens, spaces, or special characters allowed. Examples of valid
usernames: johndoe, alice_smith, dev123, elixir_fan. Examples of invalid:
JohnDoe (uppercase), 123user (starts with number), jo (too short), john-doe
(hyphen not allowed), admin (reserved word).
',
  'Käyttäjätunnuksen on oltava 3-30 merkkiä pitkä, aloitettava pienellä kirjaimella
(a-z) ja sisältää vain pieniä kirjaimia, numeroita ja alaviivoja. Isot kirjaimet,
väliviivat, välilyönnit tai erikoismerkit eivät ole sallittuja. Esimerkkejä
kelvollisista käyttäjätunnuksista: johndoe, alice_smith, dev123, elixir_fan.
Esimerkkejä virheellisistä: JohnDoe (isot kirjaimet), 123user (alkaa numerolla),
jo (liian lyhyt), john-doe (väliviiva ei sallittu), admin (varattu sana).
',
  70,
  true,
  '2025-12-01T13:10:41Z',
  '2025-12-01T13:10:41Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'changing-username-effects',
  'user',
  'What happens if I change my username?',
  'Mitä tapahtuu, jos vaihdan käyttäjätunnukseni?',
  'When you change your username, the new @username URL works immediately, but
old @username URLs return 404 (not found). Your numeric ID URL (/users/123)
continues to work. The old username becomes available for others to claim.
RSS feed subscriptions using the old username will break - you''ll need to share
new feed URLs with subscribers. All username changes are logged with timestamp,
IP address, and user agent for security. Choose usernames carefully as frequent
changes confuse followers.
',
  'Kun vaihdat käyttäjätunnuksesi, uusi @käyttäjätunnus-URL toimii välittömästi,
mutta vanha @käyttäjätunnus-URL palauttaa 404 (ei löydy). Numeerinen ID-URL
(/users/123) toimii edelleen. Vanha käyttäjätunnus tulee muiden varattavaksi.
RSS-syötetilaukset vanhalla käyttäjätunnuksella rikkoutuvat - sinun on jaettava
uudet syöte-URL:t tilaajille. Kaikki käyttäjätunnusten vaihdot kirjataan
aikaleimalla, IP-osoitteella ja käyttäjäagentilla turvallisuussyistä. Valitse
käyttäjätunnukset huolellisesti, sillä toistuvat muutokset hämmentävät seuraajia.
',
  80,
  true,
  '2025-12-01T13:10:41Z',
  '2025-12-01T13:10:41Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'username-in-feed-urls',
  'user',
  'Can I use my username in RSS feed URLs?',
  'Voinko käyttää käyttäjätunnustani RSS-syöte-URL:issa?',
  'Yes! Once you set a username, all feed formats support it: RSS at
/users/@yourusername/rss.xml, Atom at /users/@yourusername/feed.xml, and
JSON Feed at /users/@yourusername/feed.json. These URLs are more memorable
and professional than numeric IDs. Share these with RSS readers like Feedly,
Inoreader, NetNewsWire, or email newsletter services. Your feeds include only
published posts, sorted by publication date.
',
  'Kyllä! Kun olet asettanut käyttäjätunnuksen, kaikki syötemuodot tukevat sitä:
RSS osoitteessa /users/@käyttäjätunnuksesi/rss.xml, Atom osoitteessa
/users/@käyttäjätunnuksesi/feed.xml ja JSON Feed osoitteessa
/users/@käyttäjätunnuksesi/feed.json. Nämä URL:t ovat helpommin muistettavia
ja ammattimaisempia kuin numeeriset ID:t. Jaa nämä RSS-lukijoiden kanssa kuten
Feedly, Inoreader, NetNewsWire tai sähköpostilistan palveluiden kanssa. Syötteesi
sisältävät vain julkaistut artikkelit, järjestettynä julkaisupäivän mukaan.
',
  90,
  true,
  '2025-12-01T13:10:41Z',
  '2025-12-01T13:10:41Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'how-to-register',
  'user',
  'How do I register for an account?',
  'Miten rekisteröidyn käyttäjäksi?',
  '<p>To register for an account, you need an <strong>invitation code</strong> from an existing user or administrator. Here''s how:</p>
<ol>
  <li>Click "Log in" in the navigation menu</li>
  <li>Click "Register" on the login page</li>
  <li>Enter your email address, choose a secure password (minimum 8 characters)</li>
  <li>Enter your invitation code in the designated field</li>
  <li>Click "Create account"</li>
</ol>
<p>After registration, you''ll receive a confirmation email. Click the link to verify your account and gain full access.</p>
',
  '<p>Rekisteröityäksesi tarvitset <strong>kutsukoodin</strong> olemassa olevalta käyttäjältä tai ylläpitäjältä. Toimi näin:</p>
<ol>
  <li>Klikkaa "Kirjaudu" navigaatiovalikossa</li>
  <li>Klikkaa "Rekisteröidy" kirjautumissivulla</li>
  <li>Syötä sähköpostiosoitteesi ja valitse turvallinen salasana (vähintään 8 merkkiä)</li>
  <li>Syötä kutsukoodisi sille varattuun kenttään</li>
  <li>Klikkaa "Luo tili"</li>
</ol>
<p>Rekisteröitymisen jälkeen saat vahvistussähköpostin. Klikkaa linkkiä vahvistaaksesi tilisi ja saadaksesi täyden käyttöoikeuden.</p>
',
  100,
  true,
  '2025-12-08T12:14:39Z',
  '2025-12-08T12:14:39Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'reserved-usernames-explanation',
  'user',
  'Why can''t I use certain usernames like ''admin'' or ''api''?',
  'Miksi en voi käyttää tiettyjä käyttäjätunnuksia kuten ''admin'' tai ''api''?',
  'Over 30 usernames are reserved for system routes and administrative functions
to prevent routing conflicts. Reserved words include: admin, api, app, auth,
blog, dashboard, dev, docs, feed, feeds, help, home, login, logout, new, posts,
public, register, rss, search, settings, signup, staff, static, support, system,
tags, test, user, users, www. These ensure the application''s core functionality
remains accessible and prevents confusion between user profiles and system pages.
',
  'Yli 30 käyttäjätunnusta on varattu järjestelmäreiteille ja hallinnollisille
toiminnoille reitityskonfliktin estämiseksi. Varatut sanat sisältävät: admin,
api, app, auth, blog, dashboard, dev, docs, feed, feeds, help, home, login,
logout, new, posts, public, register, rss, search, settings, signup, staff,
static, support, system, tags, test, user, users, www. Nämä varmistavat, että
sovelluksen ydintoiminnot pysyvät saavutettavina ja estävät sekaannukset
käyttäjäprofiilien ja järjestelmäsivujen välillä.
',
  100,
  true,
  '2025-12-01T13:10:41Z',
  '2025-12-01T13:10:41Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'how-to-login',
  'user',
  'How do I log in to my account?',
  'Miten kirjaudun tililleni?',
  '<p>There are two ways to log in:</p>
<h4>Standard Login (Email + Password)</h4>
<ol>
  <li>Click "Log in" in the navigation</li>
  <li>Enter your registered email address</li>
  <li>Enter your password</li>
  <li>Click "Log in"</li>
</ol>
<h4>Magic Link (Passwordless)</h4>
<ol>
  <li>On the login page, click "Sign in with email link"</li>
  <li>Enter your email address</li>
  <li>Check your inbox for the magic link email</li>
  <li>Click the link to log in instantly (valid for 15 minutes)</li>
</ol>
<p><strong>Tip:</strong> Enable "Remember me" to stay logged in on trusted devices.</p>
',
  '<p>Kirjautumiseen on kaksi tapaa:</p>
<h4>Tavallinen kirjautuminen (sähköposti + salasana)</h4>
<ol>
  <li>Klikkaa "Kirjaudu" navigaatiossa</li>
  <li>Syötä rekisteröity sähköpostiosoitteesi</li>
  <li>Syötä salasanasi</li>
  <li>Klikkaa "Kirjaudu"</li>
</ol>
<h4>Taikainkki (salasanaton)</h4>
<ol>
  <li>Klikkaa kirjautumissivulla "Kirjaudu sähköpostilinkillä"</li>
  <li>Syötä sähköpostiosoitteesi</li>
  <li>Tarkista sähköpostisi taikalinkkiviestin varalta</li>
  <li>Klikkaa linkkiä kirjautuaksesi välittömästi (voimassa 15 minuuttia)</li>
</ol>
<p><strong>Vinkki:</strong> Ota "Muista minut" käyttöön pysyäksesi kirjautuneena luotetuilla laitteilla.</p>
',
  110,
  true,
  '2025-12-08T12:14:39Z',
  '2025-12-08T12:14:39Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'reset-password',
  'user',
  'How do I reset my password?',
  'Miten nollaan salasanani?',
  '<p>If you''ve forgotten your password:</p>
<ol>
  <li>Go to the login page and click "Forgot password?"</li>
  <li>Enter your registered email address</li>
  <li>Click "Send reset instructions"</li>
  <li>Check your email for the reset link (valid for 1 hour)</li>
  <li>Click the link and enter your new password (minimum 8 characters)</li>
  <li>Confirm by entering the password again</li>
</ol>
<p><strong>Security note:</strong> The reset link can only be used once. For security reasons, we don''t confirm whether an email exists in our system.</p>
',
  '<p>Jos olet unohtanut salasanasi:</p>
<ol>
  <li>Mene kirjautumissivulle ja klikkaa "Unohditko salasanan?"</li>
  <li>Syötä rekisteröity sähköpostiosoitteesi</li>
  <li>Klikkaa "Lähetä nollausohjeet"</li>
  <li>Tarkista sähköpostisi nollauslinkin varalta (voimassa 1 tunti)</li>
  <li>Klikkaa linkkiä ja syötä uusi salasanasi (vähintään 8 merkkiä)</li>
  <li>Vahvista syöttämällä salasana uudelleen</li>
</ol>
<p><strong>Turvallisuushuomautus:</strong> Nollauslinkkiä voi käyttää vain kerran. Turvallisuussyistä emme vahvista, onko sähköpostiosoite järjestelmässämme.</p>
',
  120,
  true,
  '2025-12-08T12:14:39Z',
  '2025-12-08T12:14:39Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'dashboard-overview',
  'user',
  'What is the Dashboard and what can I do there?',
  'Mikä on kojelauta ja mitä siellä voi tehdä?',
  '<p>The <strong>Dashboard</strong> is your personal command center showing:</p>
<ul>
  <li><strong>Statistics:</strong> Total posts, tags, and views at a glance</li>
  <li><strong>Recent Activity:</strong> Your latest posts and interactions</li>
  <li><strong>Quick Actions:</strong> Shortcuts to create new posts or manage tags</li>
  <li><strong>Feed Updates:</strong> Latest items from your subscribed external feeds</li>
</ul>
<p>Access your dashboard anytime by clicking "Dashboard" in the navigation menu after logging in.</p>
',
  '<p><strong>Kojelauta</strong> on henkilökohtainen komentokeskuksesi, joka näyttää:</p>
<ul>
  <li><strong>Tilastot:</strong> Julkaisujen, tagien ja katseluiden kokonaismäärä yhdellä silmäyksellä</li>
  <li><strong>Viimeaikainen toiminta:</strong> Uusimmat julkaisusi ja vuorovaikutuksesi</li>
  <li><strong>Pikatoiminnot:</strong> Pikakuvakkeet uusien julkaisujen luomiseen tai tagien hallintaan</li>
  <li><strong>Syötepäivitykset:</strong> Uusimmat kohteet tilaamistasi ulkoisista syötteistä</li>
</ul>
<p>Pääset kojelautaan milloin tahansa klikkaamalla "Kojelauta" navigaatiovalikossa kirjautumisen jälkeen.</p>
',
  130,
  true,
  '2025-12-08T12:14:39Z',
  '2025-12-08T12:14:39Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'create-blog-post',
  'user',
  'How do I create a new blog post?',
  'Miten luon uuden blogikirjoituksen?',
  '<p>Creating a blog post is simple:</p>
<ol>
  <li>Click "Posts" in the navigation menu</li>
  <li>Click the "New Post" button</li>
  <li>Enter a compelling title for your post</li>
  <li>Write your content using Markdown formatting</li>
  <li>Add relevant tags to categorize your post</li>
  <li>Set a publication date (leave blank for immediate publishing)</li>
  <li>Click "Save" to publish or "Save as Draft" to continue later</li>
</ol>
<p><strong>Tip:</strong> Use the preview feature to see how your post will look before publishing.</p>
',
  '<p>Blogikirjoituksen luominen on helppoa:</p>
<ol>
  <li>Klikkaa "Julkaisut" navigaatiovalikossa</li>
  <li>Klikkaa "Uusi julkaisu" -painiketta</li>
  <li>Syötä kiinnostava otsikko julkaisullesi</li>
  <li>Kirjoita sisältösi käyttäen Markdown-muotoilua</li>
  <li>Lisää relevantteja tageja julkaisusi luokittelemiseksi</li>
  <li>Aseta julkaisupäivä (jätä tyhjäksi välittömään julkaisuun)</li>
  <li>Klikkaa "Tallenna" julkaistaksesi tai "Tallenna luonnoksena" jatkaaksesi myöhemmin</li>
</ol>
<p><strong>Vinkki:</strong> Käytä esikatselutoimintoa nähdäksesi miltä julkaisusi näyttää ennen julkaisua.</p>
',
  200,
  true,
  '2025-12-08T12:14:39Z',
  '2025-12-08T12:14:39Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'markdown-formatting',
  'user',
  'What Markdown formatting is supported?',
  'Mitä Markdown-muotoilua tuetaan?',
  '<p>Our editor supports full <strong>GitHub Flavored Markdown</strong> with these features:</p>
<ul>
  <li><strong>Headers:</strong> Use # for h1, ## for h2, etc.</li>
  <li><strong>Text styling:</strong> **bold**, *italic*, ~~strikethrough~~</li>
  <li><strong>Lists:</strong> Numbered (1. 2. 3.) and bullet points (- or *)</li>
  <li><strong>Links:</strong> [text](url) or auto-linked URLs</li>
  <li><strong>Images:</strong> ![alt text](image-url)</li>
  <li><strong>Code:</strong> Inline `code` and fenced code blocks with syntax highlighting</li>
  <li><strong>Tables:</strong> Using pipe | characters</li>
  <li><strong>Task lists:</strong> - [ ] unchecked, - [x] checked</li>
  <li><strong>Blockquotes:</strong> > for quoted text</li>
</ul>
<p>Code blocks support syntax highlighting for Elixir, JavaScript, Python, and 100+ languages.</p>
',
  '<p>Editorimme tukee täydellistä <strong>GitHub Flavored Markdownia</strong> näillä ominaisuuksilla:</p>
<ul>
  <li><strong>Otsikot:</strong> Käytä # h1:lle, ## h2:lle jne.</li>
  <li><strong>Tekstin muotoilu:</strong> **lihavoitu**, *kursivoitu*, ~~yliviivattu~~</li>
  <li><strong>Listat:</strong> Numeroidut (1. 2. 3.) ja luettelomerkit (- tai *)</li>
  <li><strong>Linkit:</strong> [teksti](url) tai automaattisesti linkitetyt URL:t</li>
  <li><strong>Kuvat:</strong> ![vaihtoehtoinen teksti](kuvan-url)</li>
  <li><strong>Koodi:</strong> Rivikoodi `koodi` ja koodilohkot syntaksikorostuksella</li>
  <li><strong>Taulukot:</strong> Käyttäen pystyviivaa |</li>
  <li><strong>Tehtävälistat:</strong> - [ ] valitsematon, - [x] valittu</li>
  <li><strong>Lainaukset:</strong> > lainatulle tekstille</li>
</ul>
<p>Koodilohkot tukevat syntaksikorostusta Elixirille, JavaScriptille, Pythonille ja yli 100 muulle kielelle.</p>
',
  210,
  true,
  '2025-12-08T12:14:39Z',
  '2025-12-08T12:14:39Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'edit-delete-post',
  'user',
  'How do I edit or delete a post?',
  'Miten muokkaan tai poistan julkaisun?',
  '<p><strong>To edit a post:</strong></p>
<ol>
  <li>Go to "Posts" and find the post you want to edit</li>
  <li>Click the post title to view it, then click "Edit post"</li>
  <li>Or click the edit icon (pencil) directly from the post list</li>
  <li>Make your changes and click "Save"</li>
</ol>
<p><strong>To delete a post:</strong></p>
<ol>
  <li>Open the post you want to delete</li>
  <li>Click the "Delete" button</li>
  <li>Confirm the deletion when prompted</li>
</ol>
<p><strong>Warning:</strong> Deleted posts cannot be recovered. Consider unpublishing instead by clearing the publication date.</p>
',
  '<p><strong>Julkaisun muokkaaminen:</strong></p>
<ol>
  <li>Mene "Julkaisut"-osioon ja etsi muokattava julkaisu</li>
  <li>Klikkaa julkaisun otsikkoa nähdäksesi sen, sitten klikkaa "Muokkaa julkaisua"</li>
  <li>Tai klikkaa muokkauskuvaketta (kynä) suoraan julkaisulistasta</li>
  <li>Tee muutoksesi ja klikkaa "Tallenna"</li>
</ol>
<p><strong>Julkaisun poistaminen:</strong></p>
<ol>
  <li>Avaa julkaisu, jonka haluat poistaa</li>
  <li>Klikkaa "Poista"-painiketta</li>
  <li>Vahvista poisto pyydettäessä</li>
</ol>
<p><strong>Varoitus:</strong> Poistettuja julkaisuja ei voi palauttaa. Harkitse julkaisun poistamista julkisesta näkyvyydestä tyhjentämällä julkaisupäivä.</p>
',
  220,
  true,
  '2025-12-08T12:14:39Z',
  '2025-12-08T12:14:39Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'post-visibility',
  'user',
  'Who can see my posts?',
  'Kuka voi nähdä julkaisuni?',
  '<p>Post visibility depends on the publication status:</p>
<ul>
  <li><strong>Published posts</strong> (with a publication date): Visible to everyone, including non-logged-in visitors</li>
  <li><strong>Draft posts</strong> (no publication date): Only visible to you</li>
  <li><strong>Future-dated posts:</strong> Hidden until the publication date arrives</li>
</ul>
<p>Published posts appear on:</p>
<ul>
  <li>Your public profile page (/users/@username)</li>
  <li>Tag pages for any tags you''ve assigned</li>
  <li>Site-wide search results</li>
  <li>RSS/Atom/JSON feeds</li>
</ul>
',
  '<p>Julkaisun näkyvyys riippuu julkaisutilasta:</p>
<ul>
  <li><strong>Julkaistut julkaisut</strong> (julkaisupäivän kanssa): Näkyvät kaikille, mukaan lukien kirjautumattomille vierailijoille</li>
  <li><strong>Luonnosjulkaisut</strong> (ei julkaisupäivää): Näkyvät vain sinulle</li>
  <li><strong>Tulevaisuuteen ajastetut julkaisut:</strong> Piilotettu kunnes julkaisupäivä koittaa</li>
</ul>
<p>Julkaistut julkaisut näkyvät:</p>
<ul>
  <li>Julkisella profiilisivullasi (/users/@käyttäjätunnus)</li>
  <li>Tagisivuilla määrittämillesi tageille</li>
  <li>Sivuston hakutuloksissa</li>
  <li>RSS/Atom/JSON-syötteissä</li>
</ul>
',
  230,
  true,
  '2025-12-08T12:14:39Z',
  '2025-12-08T12:14:39Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'create-use-tags',
  'user',
  'How do I create and use tags?',
  'Miten luon ja käytän tageja?',
  '<p><strong>Creating tags:</strong></p>
<ol>
  <li>Go to "Tags" in the navigation</li>
  <li>Click "New Tag"</li>
  <li>Enter a name (unique, descriptive)</li>
  <li>Optionally add a description</li>
  <li>Click "Save"</li>
</ol>
<p><strong>Using tags in posts:</strong></p>
<ol>
  <li>When creating or editing a post, find the "Tags" field</li>
  <li>Select existing tags from the dropdown</li>
  <li>Posts can have multiple tags</li>
</ol>
<p><strong>Benefits of tags:</strong></p>
<ul>
  <li>Help readers find related content</li>
  <li>Organize your posts by topic</li>
  <li>Each tag has its own page showing all tagged posts</li>
</ul>
',
  '<p><strong>Tagien luominen:</strong></p>
<ol>
  <li>Mene "Tagit"-osioon navigaatiossa</li>
  <li>Klikkaa "Uusi tagi"</li>
  <li>Syötä nimi (uniikki, kuvaava)</li>
  <li>Lisää valinnaisesti kuvaus</li>
  <li>Klikkaa "Tallenna"</li>
</ol>
<p><strong>Tagien käyttö julkaisuissa:</strong></p>
<ol>
  <li>Julkaisua luodessa tai muokatessa etsi "Tagit"-kenttä</li>
  <li>Valitse olemassa olevia tageja pudotusvalikosta</li>
  <li>Julkaisuilla voi olla useita tageja</li>
</ol>
<p><strong>Tagien hyödyt:</strong></p>
<ul>
  <li>Auttavat lukijoita löytämään liittyvää sisältöä</li>
  <li>Järjestävät julkaisusi aiheen mukaan</li>
  <li>Jokaisella tagilla on oma sivu, joka näyttää kaikki tagitetyt julkaisut</li>
</ul>
',
  300,
  true,
  '2025-12-08T12:14:39Z',
  '2025-12-08T12:14:39Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'change-email',
  'user',
  'How do I change my email address?',
  'Miten vaihdan sähköpostiosoitteeni?',
  '<p>To change your email address:</p>
<ol>
  <li>Go to Settings → Email section</li>
  <li>Enter your new email address</li>
  <li>Enter your current password to confirm</li>
  <li>Click "Change email"</li>
  <li>Check your new email for a confirmation link</li>
  <li>Click the confirmation link to activate the new address</li>
</ol>
<p><strong>Important:</strong> Your old email remains active until you confirm the new one. The confirmation link expires after 1 hour.</p>
',
  '<p>Sähköpostiosoitteen vaihtaminen:</p>
<ol>
  <li>Mene Asetukset → Sähköposti-osioon</li>
  <li>Syötä uusi sähköpostiosoitteesi</li>
  <li>Syötä nykyinen salasanasi vahvistaaksesi</li>
  <li>Klikkaa "Vaihda sähköposti"</li>
  <li>Tarkista uusi sähköpostisi vahvistuslinkin varalta</li>
  <li>Klikkaa vahvistuslinkkiä aktivoidaksesi uuden osoitteen</li>
</ol>
<p><strong>Tärkeää:</strong> Vanha sähköpostisi pysyy aktiivisena kunnes vahvistat uuden. Vahvistuslinkki vanhenee 1 tunnin kuluttua.</p>
',
  410,
  true,
  '2025-12-08T12:14:39Z',
  '2025-12-08T12:14:39Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'change-password',
  'user',
  'How do I change my password?',
  'Miten vaihdan salasanani?',
  '<p>To change your password while logged in:</p>
<ol>
  <li>Go to Settings → Password section</li>
  <li>Enter your current password</li>
  <li>Enter your new password (minimum 8 characters)</li>
  <li>Confirm by entering the new password again</li>
  <li>Click "Change password"</li>
</ol>
<p><strong>Password requirements:</strong></p>
<ul>
  <li>Minimum 8 characters</li>
  <li>Mix of letters, numbers, and symbols recommended</li>
  <li>Avoid common words or personal information</li>
</ul>
',
  '<p>Salasanan vaihtaminen kirjautuneena:</p>
<ol>
  <li>Mene Asetukset → Salasana-osioon</li>
  <li>Syötä nykyinen salasanasi</li>
  <li>Syötä uusi salasanasi (vähintään 8 merkkiä)</li>
  <li>Vahvista syöttämällä uusi salasana uudelleen</li>
  <li>Klikkaa "Vaihda salasana"</li>
</ol>
<p><strong>Salasanavaatimukset:</strong></p>
<ul>
  <li>Vähintään 8 merkkiä</li>
  <li>Suositellaan kirjainten, numeroiden ja symbolien yhdistelmää</li>
  <li>Vältä yleisiä sanoja tai henkilökohtaisia tietoja</li>
</ul>
',
  420,
  true,
  '2025-12-08T12:14:39Z',
  '2025-12-08T12:14:39Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'subscribe-to-blog',
  'user',
  'How can readers subscribe to my blog?',
  'Miten lukijat voivat tilata blogini?',
  '<p>Your blog automatically provides feeds in three formats:</p>
<ul>
  <li><strong>RSS:</strong> <code>/users/@username/rss.xml</code></li>
  <li><strong>Atom:</strong> <code>/users/@username/feed.xml</code></li>
  <li><strong>JSON Feed:</strong> <code>/users/@username/feed.json</code></li>
</ul>
<p>Readers can subscribe using any feed reader like Feedly, Inoreader, NetNewsWire, or Newsblur.</p>
<p>The site also provides global feeds:</p>
<ul>
  <li>RSS: <code>/rss.xml</code></li>
  <li>Atom: <code>/feed.xml</code></li>
  <li>JSON: <code>/feed.json</code></li>
</ul>
<p>Feed links are automatically included in your page''s HTML for autodiscovery.</p>
',
  '<p>Blogisi tarjoaa automaattisesti syötteet kolmessa muodossa:</p>
<ul>
  <li><strong>RSS:</strong> <code>/users/@käyttäjätunnus/rss.xml</code></li>
  <li><strong>Atom:</strong> <code>/users/@käyttäjätunnus/feed.xml</code></li>
  <li><strong>JSON Feed:</strong> <code>/users/@käyttäjätunnus/feed.json</code></li>
</ul>
<p>Lukijat voivat tilata millä tahansa syötteenlukijalla kuten Feedly, Inoreader, NetNewsWire tai Newsblur.</p>
<p>Sivusto tarjoaa myös yleiset syötteet:</p>
<ul>
  <li>RSS: <code>/rss.xml</code></li>
  <li>Atom: <code>/feed.xml</code></li>
  <li>JSON: <code>/feed.json</code></li>
</ul>
<p>Syötelinkit sisällytetään automaattisesti sivusi HTML:ään automaattista löytämistä varten.</p>
',
  500,
  true,
  '2025-12-08T12:14:39Z',
  '2025-12-08T12:14:39Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'search-content',
  'user',
  'How do I search for content?',
  'Miten haen sisältöä?',
  '<p>Use the <strong>Search</strong> feature in the navigation to find content:</p>
<ol>
  <li>Click the search icon or "Search" in the menu</li>
  <li>Enter your search terms</li>
  <li>Press Enter or click Search</li>
</ol>
<p><strong>Search finds:</strong></p>
<ul>
  <li>Blog posts (titles and content)</li>
  <li>Tags (names and descriptions)</li>
  <li>FAQs (questions and answers)</li>
</ul>
<p><strong>Tips:</strong></p>
<ul>
  <li>Use multiple keywords for more specific results</li>
  <li>Search is case-insensitive</li>
  <li>Results are ranked by relevance</li>
</ul>
',
  '<p>Käytä <strong>Haku</strong>-toimintoa navigaatiossa sisällön löytämiseen:</p>
<ol>
  <li>Klikkaa hakukuvaketta tai "Haku" valikossa</li>
  <li>Syötä hakusanasi</li>
  <li>Paina Enter tai klikkaa Hae</li>
</ol>
<p><strong>Haku löytää:</strong></p>
<ul>
  <li>Blogikirjoitukset (otsikot ja sisältö)</li>
  <li>Tagit (nimet ja kuvaukset)</li>
  <li>Usein kysytyt kysymykset (kysymykset ja vastaukset)</li>
</ul>
<p><strong>Vinkkejä:</strong></p>
<ul>
  <li>Käytä useita avainsanoja tarkempiin tuloksiin</li>
  <li>Haku ei erottele isoja ja pieniä kirjaimia</li>
  <li>Tulokset järjestetään relevanssin mukaan</li>
</ul>
',
  600,
  true,
  '2025-12-08T12:14:39Z',
  '2025-12-08T12:14:39Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'upload-manage-media',
  'user',
  'How do I upload and manage media files?',
  'Miten lataan ja hallinnoin mediatiedostoja?',
  '<p>The <strong>Media Library</strong> lets you upload and organize images and files:</p>
<ol>
  <li>Go to "Media" in the navigation</li>
  <li>Click "Upload" or drag files into the upload area</li>
  <li>Supported formats: JPG, PNG, GIF, WebP (images), PDF (documents)</li>
  <li>Maximum file size: 10MB per file</li>
</ol>
<p><strong>Organizing media:</strong></p>
<ul>
  <li>Add tags to categorize your media</li>
  <li>Use the search to find specific files</li>
  <li>Click any item to view details and get embed URLs</li>
</ul>
<p><strong>Using in posts:</strong> Copy the media URL and use Markdown image syntax: <code>![description](url)</code></p>
',
  '<p><strong>Mediakirjasto</strong> mahdollistaa kuvien ja tiedostojen lataamisen ja järjestämisen:</p>
<ol>
  <li>Mene "Media"-osioon navigaatiossa</li>
  <li>Klikkaa "Lataa" tai vedä tiedostot latausahueelle</li>
  <li>Tuetut muodot: JPG, PNG, GIF, WebP (kuvat), PDF (dokumentit)</li>
  <li>Maksimitiedostokoko: 10MB per tiedosto</li>
</ol>
<p><strong>Median järjestäminen:</strong></p>
<ul>
  <li>Lisää tageja median luokittelemiseksi</li>
  <li>Käytä hakua tiettyjen tiedostojen löytämiseen</li>
  <li>Klikkaa kohdetta nähdäksesi yksityiskohdat ja saadaksesi upotus-URL:t</li>
</ul>
<p><strong>Käyttö julkaisuissa:</strong> Kopioi median URL ja käytä Markdown-kuvasyntaksia: <code>![kuvaus](url)</code></p>
',
  700,
  true,
  '2025-12-08T12:14:39Z',
  '2025-12-08T12:14:39Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'projects-overview',
  'user',
  'What are Projects and how do I use them?',
  'Mitä projektit ovat ja miten niitä käytetään?',
  '<p><strong>Projects</strong> let you showcase your work in organized collections:</p>
<h4>Project Types:</h4>
<ul>
  <li><strong>Portfolio:</strong> Showcase your best work publicly</li>
  <li><strong>Library:</strong> Organize media into private collections</li>
</ul>
<h4>Creating a project:</h4>
<ol>
  <li>Go to "Projects" in the navigation</li>
  <li>Click "New Project"</li>
  <li>Choose a type (Portfolio or Library)</li>
  <li>Add a title, description, and cover image</li>
  <li>Add media items to the project</li>
  <li>Set visibility (public or private)</li>
</ol>
<p>Portfolio projects are displayed on your public profile page for visitors to browse.</p>
',
  '<p><strong>Projektit</strong> mahdollistavat työnäytteiden esittelyn järjestetyissä kokoelmissa:</p>
<h4>Projektityypit:</h4>
<ul>
  <li><strong>Portfolio:</strong> Esittele parhaita töitäsi julkisesti</li>
  <li><strong>Kirjasto:</strong> Järjestä media yksityisiin kokoelmiin</li>
</ul>
<h4>Projektin luominen:</h4>
<ol>
  <li>Mene "Projektit"-osioon navigaatiossa</li>
  <li>Klikkaa "Uusi projekti"</li>
  <li>Valitse tyyppi (Portfolio tai Kirjasto)</li>
  <li>Lisää otsikko, kuvaus ja kansikuva</li>
  <li>Lisää mediakohteita projektiin</li>
  <li>Aseta näkyvyys (julkinen tai yksityinen)</li>
</ol>
<p>Portfolio-projektit näytetään julkisella profiilisivullasi vierailijoiden selattavaksi.</p>
',
  710,
  true,
  '2025-12-08T12:14:39Z',
  '2025-12-08T12:14:39Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'provide-feedback',
  'user',
  'How do I provide feedback about the site?',
  'Miten annan palautetta sivustosta?',
  '<p>We value your feedback! Here''s how to share your thoughts:</p>
<ol>
  <li>Click "Feedback" in the navigation or footer</li>
  <li>Rate your overall experience (happiness meter)</li>
  <li>Share specific feedback or suggestions</li>
  <li>Optionally allow your feedback as a testimonial</li>
  <li>Submit your feedback</li>
</ol>
<p><strong>What we''d love to hear:</strong></p>
<ul>
  <li>Features you''d like to see</li>
  <li>Issues you''ve encountered</li>
  <li>What you enjoy about the site</li>
  <li>Suggestions for improvement</li>
</ul>
<p>Your feedback helps us improve the platform for everyone!</p>
',
  '<p>Arvostamme palautettasi! Näin jaat ajatuksesi:</p>
<ol>
  <li>Klikkaa "Palaute" navigaatiossa tai alatunnisteessa</li>
  <li>Arvioi kokonaiskokemuksesi (tyytyväisyysmittari)</li>
  <li>Jaa erityistä palautetta tai ehdotuksia</li>
  <li>Valinnaisesti salli palautteesi käyttö suosituksena</li>
  <li>Lähetä palautteesi</li>
</ol>
<p><strong>Haluaisimme kuulla:</strong></p>
<ul>
  <li>Ominaisuuksia, joita haluaisit nähdä</li>
  <li>Kohtaamiasi ongelmia</li>
  <li>Mitä pidät sivustossa</li>
  <li>Parannusehdotuksia</li>
</ul>
<p>Palautteesi auttaa meitä parantamaan alustaa kaikille!</p>
',
  800,
  true,
  '2025-12-08T12:14:39Z',
  '2025-12-08T12:14:39Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

INSERT INTO faqs (
  slug, category, question_en, question_fi, answer_en, answer_fi,
  display_order, is_active, inserted_at, updated_at
) VALUES (
  'account-security',
  'user',
  'How is my account protected?',
  'Miten tilini on suojattu?',
  '<p>We take security seriously. Your account is protected by:</p>
<ul>
  <li><strong>Secure password hashing:</strong> Using Argon2, the industry standard</li>
  <li><strong>HTTPS encryption:</strong> All data is encrypted in transit</li>
  <li><strong>CSRF protection:</strong> Prevents cross-site request forgery</li>
  <li><strong>Rate limiting:</strong> Protects against brute-force attacks</li>
  <li><strong>Secure sessions:</strong> Auto-logout after inactivity</li>
</ul>
<p><strong>Best practices:</strong></p>
<ul>
  <li>Use a unique, strong password</li>
  <li>Don''t share your login credentials</li>
  <li>Log out on shared devices</li>
  <li>Report any suspicious activity</li>
</ul>
',
  '<p>Otamme turvallisuuden vakavasti. Tilisi on suojattu:</p>
<ul>
  <li><strong>Turvallinen salasanan tiivistys:</strong> Käyttäen Argon2:ta, alan standardia</li>
  <li><strong>HTTPS-salaus:</strong> Kaikki data on salattu siirron aikana</li>
  <li><strong>CSRF-suojaus:</strong> Estää sivustojen välisen pyyntöväärennöksen</li>
  <li><strong>Nopeudenrajoitus:</strong> Suojaa brute-force-hyökkäyksiltä</li>
  <li><strong>Turvalliset istunnot:</strong> Automaattinen uloskirjaus toimettomuuden jälkeen</li>
</ul>
<p><strong>Parhaat käytännöt:</strong></p>
<ul>
  <li>Käytä ainutlaatuista, vahvaa salasanaa</li>
  <li>Älä jaa kirjautumistietojasi</li>
  <li>Kirjaudu ulos jaetuilla laitteilla</li>
  <li>Ilmoita epäilyttävästä toiminnasta</li>
</ul>
',
  900,
  true,
  '2025-12-08T12:14:39Z',
  '2025-12-08T12:14:39Z'
) ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  question_en = EXCLUDED.question_en,
  question_fi = EXCLUDED.question_fi,
  answer_en = EXCLUDED.answer_en,
  answer_fi = EXCLUDED.answer_fi,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

COMMIT;

-- Export complete
