defmodule Mix.Tasks.Faq.ExportSql do
  @moduledoc """
  Exports FAQs from the database to a SQL file for production import.

  ## Usage

      mix faq.export_sql

  ## Options

    * --output - Output file path. Default: priv/repo/faq_export.sql

  ## Examples

      # Export to default location
      mix faq.export_sql

      # Export to custom file
      mix faq.export_sql --output /tmp/faqs.sql

  ## What This Task Does

  1. Loads all FAQs from the database
  2. Generates a SQL file with INSERT statements
  3. Handles conflicts with UPSERT (ON CONFLICT UPDATE)
  4. The generated file can be run directly in production

  ## Production Usage

  Run the generated SQL file in production:

      psql $DATABASE_URL < priv/repo/faq_export.sql

  Or via fly.io:

      fly ssh console -C "psql $DATABASE_URL < /app/priv/repo/faq_export.sql"
  """

  use Mix.Task
  import Ecto.Query

  alias Homesite.Faqs.Faq
  alias Homesite.Repo

  @shortdoc "Exports FAQs from database to SQL file for production import"

  @impl Mix.Task
  def run(args) do
    Mix.Task.run("app.start")

    {opts, _, _} =
      OptionParser.parse(args,
        strict: [output: :string],
        aliases: [o: :output]
      )

    output_file = Keyword.get(opts, :output, "priv/repo/faq_export.sql")

    export_faqs_to_sql(output_file)
  end

  defp export_faqs_to_sql(output_file) do
    Mix.shell().info("📤 Exporting FAQs to SQL...")

    faqs =
      Faq
      |> order_by([f], asc: f.category, asc: f.display_order)
      |> Repo.all()

    if Enum.empty?(faqs) do
      Mix.shell().error("No FAQs found in database. Nothing to export.")
      System.halt(1)
    end

    content = generate_sql_content(faqs)

    # Ensure directory exists
    output_file |> Path.dirname() |> File.mkdir_p!()

    File.write!(output_file, content)

    Mix.shell().info("""

    ✅ FAQ SQL export complete!

    Exported: #{length(faqs)} FAQs
    Output:   #{output_file}

    To import to production:

      # Local PostgreSQL
      psql $DATABASE_URL < #{output_file}

      # Fly.io
      fly ssh console -C "cat /app/#{output_file} | psql \\$DATABASE_URL"

      # Docker
      docker exec -i <container> psql $DATABASE_URL < #{output_file}
    """)
  end

  defp generate_sql_content(faqs) do
    timestamp = DateTime.utc_now() |> DateTime.to_iso8601()

    header = """
    -- FAQ Export - Generated #{timestamp}
    -- Total FAQs: #{length(faqs)}
    --
    -- This file was auto-generated by `mix faq.export_sql`
    --
    -- Usage: psql $DATABASE_URL < this_file.sql

    BEGIN;

    """

    footer = """

    COMMIT;

    -- Export complete
    """

    body = faqs |> Enum.map(&generate_insert_statement/1) |> Enum.join("\n")

    header <> body <> footer
  end

  defp generate_insert_statement(faq) do
    """
    INSERT INTO faqs (
      slug, category, question_en, question_fi, answer_en, answer_fi,
      display_order, is_active, inserted_at, updated_at
    ) VALUES (
      #{escape_sql(faq.slug)},
      #{escape_sql(faq.category)},
      #{escape_sql(faq.question_en)},
      #{escape_sql(faq.question_fi)},
      #{escape_sql(faq.answer_en)},
      #{escape_sql(faq.answer_fi)},
      #{faq.display_order},
      #{faq.is_active},
      #{escape_sql(DateTime.to_iso8601(faq.inserted_at))},
      #{escape_sql(DateTime.to_iso8601(faq.updated_at))}
    ) ON CONFLICT (slug) DO UPDATE SET
      category = EXCLUDED.category,
      question_en = EXCLUDED.question_en,
      question_fi = EXCLUDED.question_fi,
      answer_en = EXCLUDED.answer_en,
      answer_fi = EXCLUDED.answer_fi,
      display_order = EXCLUDED.display_order,
      is_active = EXCLUDED.is_active,
      updated_at = EXCLUDED.updated_at;
    """
  end

  defp escape_sql(nil), do: "NULL"

  defp escape_sql(value) when is_binary(value) do
    # PostgreSQL-style escaping: double single quotes
    escaped = String.replace(value, "'", "''")
    "'#{escaped}'"
  end
end
