defmodule Mix.Tasks.Seed.Export do
  @moduledoc """
  Exports FAQs from the database to an Elixir seed file.

  ## Usage

      mix seed.export

  ## Options

    * --output - Output file path. Default: priv/repo/seeds/faqs_export.exs

  ## Examples

      # Export to default location
      mix seed.export

      # Export to custom file
      mix seed.export --output priv/repo/seeds/my_faqs.exs

  ## What This Task Does

  1. Loads all FAQs from the database
  2. Generates an Elixir seed file with the FAQ data
  3. The generated file can be committed to git for portability

  ## Use Case

  When you edit FAQs in the admin interface and want to sync those changes
  back to the seed files for version control and deployment to other environments.
  """

  use Mix.Task
  import Ecto.Query

  alias Homesite.Faqs.Faq
  alias Homesite.Repo

  @shortdoc "Exports FAQs from database to seed file"

  @impl Mix.Task
  def run(args) do
    Mix.Task.run("app.start")

    {opts, _, _} =
      OptionParser.parse(args,
        strict: [output: :string],
        aliases: [o: :output]
      )

    output_file = Keyword.get(opts, :output, "priv/repo/seeds/faqs_export.exs")

    export_faqs(output_file)
  end

  defp export_faqs(output_file) do
    Mix.shell().info("📤 Exporting FAQs...")

    faqs =
      Faq
      |> order_by([f], asc: f.category, asc: f.display_order)
      |> Repo.all()

    if Enum.empty?(faqs) do
      Mix.shell().error("No FAQs found in database. Nothing to export.")
      System.halt(1)
    end

    content = generate_seed_content(faqs)

    # Ensure directory exists
    output_file |> Path.dirname() |> File.mkdir_p!()

    File.write!(output_file, content)

    Mix.shell().info("""

    ✅ FAQ export complete!

    Exported: #{length(faqs)} FAQs
    Output:   #{output_file}

    You can now commit this file to git:
      git add #{output_file}
      git commit -m "chore: Update FAQ seed data"

    To import on another machine:
      mix run #{output_file}
    """)
  end

  defp generate_seed_content(faqs) do
    user_faqs = Enum.filter(faqs, &(&1.category == "user"))
    admin_faqs = Enum.filter(faqs, &(&1.category == "admin"))
    timestamp = DateTime.utc_now() |> DateTime.to_iso8601()

    header = ~s"""
    # FAQ Export - Generated #{timestamp}
    # Run with: mix run priv/repo/seeds/faqs_export.exs
    #
    # This file was auto-generated by `mix seed.export`
    # Total FAQs: #{length(faqs)} (#{length(user_faqs)} user, #{length(admin_faqs)} admin)

    import Ecto.Query

    alias Homesite.Repo
    alias Homesite.Accounts
    alias Homesite.Faqs

    # Get existing admin user
    admin_user =
      Repo.one(from u in Accounts.User, where: u.role == "admin", limit: 1) ||
        raise "No admin user found. Run seeds.exs first."

    admin_scope = Accounts.Scope.for_user(admin_user)

    IO.puts("\\n=== Importing Exported FAQs ===\\n")

    # Helper function for idempotent creation
    create_faq_if_not_exists = fn faq_attrs, scope ->
      case Faqs.create_faq(scope, faq_attrs) do
        {:ok, faq} ->
          IO.puts("  ✅ Created: \#{String.slice(faq.question_en, 0, 55)}...")
          :created

        {:error, changeset} ->
          if Keyword.has_key?(changeset.errors, :slug) do
            IO.puts("  ⏭️  Exists: \#{String.slice(faq_attrs.question_en, 0, 55)}...")
            :skipped
          else
            IO.puts("  ❌ Failed: \#{String.slice(faq_attrs.question_en, 0, 55)}...")
            IO.inspect(changeset.errors, label: "    Errors")
            :failed
          end
      end
    end

    faqs = [
    """

    footer = ~s"""
    ]

    results = Enum.map(faqs, &create_faq_if_not_exists.(&1, admin_scope))

    created = Enum.count(results, &(&1 == :created))
    skipped = Enum.count(results, &(&1 == :skipped))
    failed = Enum.count(results, &(&1 == :failed))

    IO.puts("\\n=== FAQ Import Summary ===")
    IO.puts("  Created: \#{created}")
    IO.puts("  Skipped: \#{skipped} (already exist)")
    IO.puts("  Failed:  \#{failed}")
    """

    header <> generate_faq_list(faqs) <> "\n" <> footer
  end

  defp generate_faq_list(faqs) do
    faqs
    |> Enum.map(&generate_faq_map/1)
    |> Enum.join(",\n")
  end

  defp generate_faq_map(faq) do
    # Use inspect for all string values to ensure proper escaping
    "  %{\n" <>
      "    category: #{inspect(faq.category)},\n" <>
      "    question_en: #{inspect(faq.question_en)},\n" <>
      "    question_fi: #{inspect(faq.question_fi)},\n" <>
      "    answer_en: #{inspect(faq.answer_en)},\n" <>
      "    answer_fi: #{inspect(faq.answer_fi)},\n" <>
      "    display_order: #{faq.display_order},\n" <>
      "    slug: #{inspect(faq.slug)}\n" <>
      "  }"
  end
end
