defmodule Mix.Tasks.Seed.ExportTest do
  use Homesite.DataCase, async: true

  alias Mix.Tasks.Seed.Export

  import Homesite.AccountsFixtures, only: [admin_scope_fixture: 0]
  import Homesite.FaqsFixtures

  @output_path "test/tmp/faqs_export_test.exs"

  setup do
    # Clean up test output file
    File.rm(@output_path)
    on_exit(fn -> File.rm(@output_path) end)

    # Create admin scope using the proper fixture
    scope = admin_scope_fixture()

    {:ok, scope: scope}
  end

  describe "mix seed.export" do
    test "exports FAQs to a valid Elixir file", %{scope: scope} do
      # Create some test FAQs
      faq1 =
        faq_fixture(scope, %{
          category: "user",
          question_en: "Test question 1?",
          question_fi: "Testikysymys 1?",
          answer_en: "Test answer 1",
          answer_fi: "Testivastaus 1",
          display_order: 100
        })

      faq2 =
        faq_fixture(scope, %{
          category: "admin",
          question_en: "Admin question?",
          question_fi: "Ylläpitäjän kysymys?",
          answer_en: "Admin answer",
          answer_fi: "Ylläpitäjän vastaus",
          display_order: 200
        })

      # Run the export task
      Export.run(["--output", @output_path])

      # Verify file was created
      assert File.exists?(@output_path)

      # Read and verify content
      content = File.read!(@output_path)

      # Should contain header comment
      assert content =~ "# FAQ Export - Generated"
      assert content =~ "auto-generated by `mix seed.export`"

      # Should contain both FAQs
      assert content =~ "Test question 1?"
      assert content =~ "Testikysymys 1?"
      assert content =~ "Admin question?"
      assert content =~ "Ylläpitäjän kysymys?"

      # Should contain the slugs
      assert content =~ faq1.slug
      assert content =~ faq2.slug

      # Should be valid Elixir syntax (can be parsed)
      assert {:ok, _ast} = Code.string_to_quoted(content)
    end

    test "exports FAQs with multiline content correctly", %{scope: scope} do
      # Create FAQ with multiline HTML content
      _faq =
        faq_fixture(scope, %{
          category: "user",
          question_en: "How do I do something?",
          question_fi: "Miten teen jotain?",
          answer_en: """
          <p>Step 1: Do this</p>
          <p>Step 2: Do that</p>
          <ul>
            <li>Item 1</li>
            <li>Item 2</li>
          </ul>
          """,
          answer_fi: """
          <p>Vaihe 1: Tee tämä</p>
          <p>Vaihe 2: Tee tuo</p>
          """,
          display_order: 100
        })

      Export.run(["--output", @output_path])

      content = File.read!(@output_path)

      # Should be valid Elixir (multiline strings properly escaped)
      assert {:ok, _ast} = Code.string_to_quoted(content)

      # Should contain the content
      assert content =~ "Step 1: Do this"
      assert content =~ "Vaihe 1: Tee tämä"
    end

    test "exports FAQs ordered by category and display_order", %{scope: scope} do
      # Create FAQs in random order
      _faq3 = faq_fixture(scope, %{category: "user", display_order: 300, question_en: "User Q3?"})

      _faq1 =
        faq_fixture(scope, %{category: "admin", display_order: 100, question_en: "Admin Q1?"})

      _faq2 = faq_fixture(scope, %{category: "user", display_order: 100, question_en: "User Q1?"})

      Export.run(["--output", @output_path])

      content = File.read!(@output_path)

      # Find positions of each question in the output
      admin_pos = :binary.match(content, "Admin Q1?") |> elem(0)
      user1_pos = :binary.match(content, "User Q1?") |> elem(0)
      user3_pos = :binary.match(content, "User Q3?") |> elem(0)

      # Admin should come first (alphabetically by category)
      assert admin_pos < user1_pos
      # User Q1 should come before User Q3 (by display_order)
      assert user1_pos < user3_pos
    end

    test "includes summary comment with FAQ counts", %{scope: scope} do
      # Create 2 user FAQs and 1 admin FAQ
      faq_fixture(scope, %{category: "user", question_en: "User 1?"})
      faq_fixture(scope, %{category: "user", question_en: "User 2?"})
      faq_fixture(scope, %{category: "admin", question_en: "Admin 1?"})

      Export.run(["--output", @output_path])

      content = File.read!(@output_path)

      # Should show correct counts
      assert content =~ "Total FAQs: 3 (2 user, 1 admin)"
    end

    test "generates idempotent import code", %{scope: scope} do
      faq_fixture(scope, %{category: "user", question_en: "Test?"})

      Export.run(["--output", @output_path])

      content = File.read!(@output_path)

      # Should contain idempotency helper
      assert content =~ "create_faq_if_not_exists"
      assert content =~ "Keyword.has_key?(changeset.errors, :slug)"
      assert content =~ ":skipped"
    end

    test "uses default output path when not specified", %{scope: scope} do
      faq_fixture(scope, %{category: "user", question_en: "Test?"})

      default_path = "priv/repo/seeds/faqs_export.exs"

      # Clean up before and after
      File.rm(default_path)
      on_exit(fn -> File.rm(default_path) end)

      Export.run([])

      assert File.exists?(default_path)
    end
  end
end
